#FSR Autogenerated Content. DO NOT DELETE
from .query_ip import query_ip
from .query_domain import query_domain
from .query_hash import query_hash
from .query_url import query_url
from .get_feed import get_feed
 
supported_operations = {'query_ip': query_ip, 'query_domain': query_domain, 'query_hash': query_hash, 'query_url': query_url, 'get_feed': get_feed, }